version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node-browsers

    working_directory: ~/intercom-java

    steps:
      - checkout
      - run: TERM="dumb" ./gradlew dependencies
      - run: TERM="dumb" ./gradlew test
