version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    working_directory: ~/intercom-java

    steps:
      - checkout

      - run: chmod +x ./gradlew
      - run: TERM="dumb" ./gradlew dependencies
      - run: TERM="dumb" ./gradlew test
