# More information on this workflow can be found here: https://stackoverflow.com/c/intercom/questions/1270

name: FOSSA License Scan

on:
  push:
    branches:
      - fossa-fix

env:
  JAVA_VERSION: 11

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: adopt
          cache: 'gradle'
      - run: |
          TERM="dumb" ./gradlew dependencies
      - name: Run FOSSA
        uses: intercom/fossa-action@main
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
          fossa-event-receiver-token: ${{ secrets.FOSSA_EVENT_RECEIVER_TOKEN }}
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
